<?php

return [
    'name' => 'Manya',
    'beian' => '',
    'cdnurl' => '',
    'version' => '1.0.1',
    'timezone' => 'Asia/Shanghai',
    'forbiddenip' => '',
    'languages' => [
        'backend' => 'zh-cn',
        'frontend' => 'zh-cn',
    ],
    'fixedpage' => 'dashboard',
    'categorytype' => [
        'default' => 'Default',
        'page' => 'Page',
        'article' => 'Article',
        'test' => 'Test',
    ],
    'configgroup' => [
        'basic' => 'Basic',
        'email' => 'Email',
        'dictionary' => 'Dictionary',
        'user' => 'User',
        'recharge' => 'Recharge',
        'bankpay' => 'BankPay',
        'example' => 'Example',
    ],
    'mail_type' => '1',
    'mail_smtp_host' => 'smtp.qq.com',
    'mail_smtp_port' => '465',
    'mail_smtp_user' => '10000',
    'mail_smtp_pass' => 'password',
    'mail_verify_type' => '2',
    'mail_from' => '10000@qq.com',
    'linegroup' => '{"事业一群":"56565656565","事业二群":"11112222222"}',
    'bank_kaihu' => '007  第一商業銀行',
    'bank_add' => '麻豆分行',
    'bank_num' => '622-57-013151',
    'recharge_money' => '5000',
    'luodiurl' => 'https://www.manyajp.com',
    'payisok' => '0',
    'rechargeline' => 'shopyjp',
    'lineimages' => '/uploads/20210720/3e22b09ed27e608858eb852cdee15f6c.jpg',
    'lineurl' => 'https://line.me/ti/p/atvAoRnXSw',
    'shanghuurl' => 'https://admin.manyajp.com/index/wanlshop/entry.html',
];
