<?php

return [
    [
        'name'    => 'rechargetips',
        'title'   => '充值提示文字',
        'type'    => 'text',
        'content' => [],
        'value'   => '余额可用于购买商品或用于商城消费',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'moneylist',
        'title'   => '充值金额列表',
        'type'    => 'array',
        'content' => [],
        'value'   => [
            '￥10'  => '10',
            '￥20'  => '20',
            '￥30'  => '30',
            '￥50'  => '50',
            '￥100' => '100',
        ],
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'defaultmoney',
        'title'   => '默认充值金额',
        'type'    => 'string',
        'content' => [],
        'value'   => '10',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'minmoney',
        'title'   => '最低充值金额',
        'type'    => 'string',
        'content' => [],
        'value'   => '0.1',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '最低的充值金额',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'iscustommoney',
        'title'   => '是否开启任意金额',
        'type'    => 'radio',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value'   => '1',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'paytypelist',
        'title'   => '支付方式',
        'type'    => 'checkbox',
        'content' => [
            'wechat' => '微信支付',
            'alipay' => '支付宝支付',
        ],
        'value'   => 'wechat,alipay',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'defaultpaytype',
        'title'   => '默认支付方式',
        'type'    => 'radio',
        'content' => [
            'wechat' => '微信支付',
            'alipay' => '支付宝支付',
        ],
        'value'   => 'wechat',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'ordercreatelimit',
        'title'   => '订单生成限制',
        'type'    => 'radio',
        'content' => [
            1 => '限制',
            0 => '不限制',
        ],
        'value'   => '0',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '是否限制未支付相同金额的订单在30分钟内只生成一次',
        'ok'      => '',
        'extend'  => '',
    ],
];
